# Generated by Django 5.1.15 on 2026-05-15 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_ends_after_starts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events_attendance',
                'indexes': [models.Index(fields=['event', '-created_at'], name='attendance_event_created_idx'), models.Index(fields=['user', '-created_at'], name='attendance_user_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='attendance_unique_event_user')],
            },
        ),
    ]
