# Generated by Django 5.1.15 on 2026-05-10 21:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('comment', models.CharField(blank=True, default='', max_length=500)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='places.placephoto')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins', to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkins_checkin',
                'indexes': [models.Index(fields=['user', '-created_at'], name='checkin_user_created_idx'), models.Index(fields=['place', '-created_at'], name='checkin_place_created_idx')],
            },
        ),
    ]
