[mypy]
python_version = 3.12
plugins = mypy_django_plugin.main, mypy_drf_plugin.main
strict_optional = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_untyped_defs = False
check_untyped_defs = True
ignore_missing_imports = False

[mypy.plugins.django-stubs]
django_settings_module = "config.settings.dev"

[mypy-*.migrations.*]
ignore_errors = True

[mypy-celery.*]
ignore_missing_imports = True