# Generated by Django 5.1.15 on 2026-05-10 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('signup', 'Signup'), ('checkin', 'Checkin'), ('first_checkin', 'First check-in'), ('referral', 'Referral')], max_length=32)),
                ('ref_type', models.CharField(blank=True, default='', max_length=64)),
                ('ref_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_points_tx',
                'indexes': [models.Index(fields=['user', '-created_at'], name='pointstx_user_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ref_id__isnull', False)), fields=('user', 'reason', 'ref_type', 'ref_id'), name='pointstx_idempotency'), models.UniqueConstraint(condition=models.Q(('ref_id__isnull', True)), fields=('user', 'reason'), name='pointstx_idempotency_no_ref')],
            },
        ),
    ]
