# Generated by Django 5.1.15 on 2026-05-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='reason',
            field=models.CharField(choices=[('checkin', 'Checkin'), ('first_checkin', 'First check-in at place'), ('friend_added', 'Friend added')], max_length=32),
        ),
    ]
