# Generated by Django 5.1.15 on 2026-05-15 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_pointstransaction_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name_ru', models.CharField(max_length=128)),
                ('description_ru', models.CharField(max_length=512)),
                ('icon_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'db_table': 'gamification_achievement',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='reason',
            field=models.CharField(choices=[('checkin', 'Чек-ин'), ('first_checkin', 'Первый чек-ин в месте'), ('friend_added', 'Принята заявка в друзья'), ('review_posted', 'Опубликован отзыв')], max_length=32),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='ref_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='gamification.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gamification_user_achievement',
                'indexes': [models.Index(fields=['user', '-created_at'], name='userachievement_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'achievement'), name='userachievement_unique')],
            },
        ),
    ]
