# Generated by Django 5.1.15 on 2026-05-13 13:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_avatar_url_user_avatar_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_context',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_vibes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=5),
        ),
    ]
