# Generated by Django 5.1.15 on 2026-05-10 21:04

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_kk', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Place categories',
                'db_table': 'places_category',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('hours_json', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='places', to='places.placecategory')),
            ],
            options={
                'db_table': 'places_place',
            },
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('r2_key_original', models.CharField(max_length=500)),
                ('r2_key_feed', models.CharField(blank=True, default='', max_length=500)),
                ('r2_key_thumb', models.CharField(blank=True, default='', max_length=500)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_place_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'places_photo',
            },
        ),
        migrations.CreateModel(
            name='PlaceVibe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('calm', 'Calm'), ('active', 'Active'), ('productive', 'Productive'), ('romantic', 'Romantic'), ('musical', 'Musical'), ('gaming', 'Gaming'), ('networking', 'Networking')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibes', to='places.place')),
            ],
            options={
                'db_table': 'places_vibe',
            },
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category', 'is_verified'], name='place_cat_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='placephoto',
            index=models.Index(fields=['place', '-created_at'], name='placephoto_place_created_idx'),
        ),
        migrations.AddIndex(
            model_name='placevibe',
            index=models.Index(fields=['tag'], name='placevibe_tag_idx'),
        ),
        migrations.AddConstraint(
            model_name='placevibe',
            constraint=models.UniqueConstraint(fields=('place', 'tag'), name='placevibe_unique_pair'),
        ),
    ]
