# Generated by Django 5.1.15 on 2026-05-11 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placephoto',
            name='height',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='r2_key_feed',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='r2_key_original',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='r2_key_thumb',
        ),
        migrations.RemoveField(
            model_name='placephoto',
            name='width',
        ),
        migrations.AddField(
            model_name='placephoto',
            name='asset',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='place_photo', to='media_app.mediaasset'),
            preserve_default=False,
        ),
    ]
