# Generated by Django 5.1.15 on 2026-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_placephoto_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('astana', 'Астана')], db_index=True, default='astana', max_length=32),
        ),
    ]
