# Generated by Django 5.1.15 on 2026-05-11 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('purpose', models.CharField(choices=[('avatar', 'Avatar'), ('checkin', 'Check-in photo'), ('place', 'Place photo')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('too_small', 'Image too small'), ('invalid_format', 'Cannot decode image'), ('size_exceeded', 'Uploaded size exceeds limit'), ('source_missing', 'Original not found in R2'), ('processing_error', 'Unknown processing error')], default='', max_length=30)),
                ('key_original', models.CharField(max_length=500)),
                ('key_feed', models.CharField(blank=True, default='', max_length=500)),
                ('key_thumb', models.CharField(blank=True, default='', max_length=500)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('source_bytes', models.PositiveIntegerField(default=0)),
                ('task_id', models.CharField(blank=True, default='', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_asset',
                'indexes': [models.Index(fields=['owner', 'purpose', '-created_at'], name='media_owner_purpose_idx'), models.Index(fields=['status', '-created_at'], name='media_status_idx')],
            },
        ),
    ]
