# Generated by Django 5.1.15 on 2026-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='purpose',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('checkin', 'Check-in photo'), ('place', 'Place photo'), ('review', 'Review')], db_index=True, max_length=20),
        ),
    ]
