# Generated by Django 5.1.15 on 2026-06-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0002_alter_mediaasset_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='purpose',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('checkin', 'Check-in photo'), ('place', 'Place photo'), ('review', 'Review'), ('post_image', 'Community post image'), ('post_video', 'Community post video')], db_index=True, max_length=20),
        ),
    ]
