# Generated by Django 5.1.15 on 2026-05-15 09:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('response_summary', models.JSONField(blank=True, default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cached_input_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('model', models.CharField(max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], default='ok', max_length=10)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_request_log',
                'indexes': [models.Index(fields=['user', '-created_at'], name='ailog_user_created_idx')],
            },
        ),
    ]
